name: CD - Deploy Windows App

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CI - Build, Test, Sonar (.NET Framework on Windows)"]
    types:
      - completed

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: build-output
        path: ./app

    - name: List downloaded files
      run: dir .\app\ /s
      shell: cmd

    - name: 🚀 Deploy para ambiente de produção (mock)
      run: |
        echo Simulando deploy...
        echo Copiando arquivos da pasta ./app para destino final...
        REM xcopy .\app "C:\inetpub\wwwroot\MyApp" /E /Y
      shell: cmd

    - name: ✅ Notificar sucesso (mock)
      run: echo "Deploy concluído com sucesso!"
