name: CD - Deploy Windows App

on:
  workflow_call:
    inputs:
      artifact-name:
        description: 'Nome do artifact gerado pela etapa de build'
        required: false
        default: 'build-output'
        type: string

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Download package artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}  
          path: ./artifact

      - name: List downloaded files
        run: dir .\artifact\ /s
        shell: cmd

      - name: Publish package to GitHub Packages
        run: |
          dotnet nuget push .\artifact\*.nupkg ^
            --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" ^
            --api-key "${{ secrets.GITHUB_TOKEN }}" ^
            --skip-duplicate
        shell: cmd

      - name: Notify success
        if: success()
        run: echo "Upload para GitHub Packages concluído com sucesso!"
        shell: cmd
