name: CD - Deploy Windows App

on:
  workflow_call:
    inputs:
      artifact-name:
        description: 'Nome do artifact gerado pela etapa de build'
        required: false
        default: 'build-output'
        type: string

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: build-output
        path: ./app

    - name: List downloaded files
      run: dir .\app\ /s
      shell: cmd

    - name: Publicar pacote no GitHub Packages
      run: |
        dotnet nuget push .\app\WindowsFormsApp\bin\Release\*.nupkg ^
          --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" ^
          --api-key "${{ secrets.GITHUB_TOKEN }}" ^
          --skip-duplicate
      shell: cmd

    - name: Notificar sucesso
      run: echo "Upload para GitHub Packages concluído com sucesso!"
