name: CI/CD Orquestrado

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: CI – Build, Test, Sonar e Publish
    uses: ./.github/workflows/dotnet-build-test.yml
    with:
      runSonar: true
    secrets:
      SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
      SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
      SONAR_URL: ${{ secrets.SONAR_URL }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  
  publish-local:
    needs: build
    uses: ./.github/workflows/publish-to-local-server.yml