name: CI/CD Orquestrado

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    name: CI – Build, Test e Sonar
    uses: ./.github/workflows/dotnet-build-test.yml
    with:
      runSonar: true
    secrets:
      SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
      SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
      SONAR_URL: ${{ secrets.SONAR_URL }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy:
    needs: build-and-test
    uses: ./.github/workflows/deploy.yml
    with:
      artifact-name: nupkg
